name: Rust

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Fetch submodules
      run: git submodule update --init --recursive
    - name: Run tests
      run: ./scripts/test.sh
